name: Build

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Check codestyle
      run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/geometry/main.c src/libgeometry/geometry1.c src/libgeometry/geometry1.h
